Merge back to develop
PilotDataPlatform/auth pull request #49
Opened 2022-10-31 18:26 UTC by gregmccoy

Merge main hotfixes back to develop

2022-10-31 18:34 UTC, andricDu requested changes

2022-10-31 18:34 UTC, andricDu commented on pyproject.toml
> +version = "2.0.4a0"
you should `poetry version preminor` which would give you `2.1.0a0`

2022-10-31 18:37 UTC, gregmccoy commented on pyproject.toml
> +version = "2.0.4a0"
I've updated it

2022-11-01 13:02 UTC, andricDu approved these changes

2022-11-01 13:02 UTC, merged